name: soloesport

description: Application mobile pour le club Solo Esport.

version: 1.0.0+1

environment:
  sdk: ^3.7.2


dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.8
  flutter_svg: ^2.0.17
  intl: ^0.20.2
  table_calendar: ^3.2.0
  qr_flutter: ^4.1.0
  http: ^1.3.0
  get_it: ^8.0.3
  dartz: ^0.10.1
  equatable: ^2.0.7
  internet_connection_checker: ^3.0.1
  shared_preferences: ^2.5.3
  flutter_bloc: ^9.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter

# Configuration de l'icône de l'application
flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/solo_logo.png"
  adaptive_icon_background: "#121212"
  adaptive_icon_foreground: "assets/images/solo_logo_fg.png"

# Configuration du splash screen
flutter_native_splash:
  color: "#121212"
  image: assets/images/solo_logo.png
  android: true
  ios: true
  android_gravity: center
  ios_content_mode: center


  flutter_lints: ^5.0.0


flutter:

  uses-material-design: true
  assets:
    - assets/images/
    - assets/images/players/
    - assets/images/shop/
    - assets/images/tournaments/
    - assets/images/partners/
    - assets/icons/
    - assets/animations/
    - assets/fonts/
  
  fonts:
    - family: Exo
      fonts:
        - asset: assets/fonts/exo/Exo-Regular.otf
        - asset: assets/fonts/exo/Exo-Bold.otf
          weight: 700
        - asset: assets/fonts/exo/Exo-Light.otf
          weight: 300
    - family: Orbitron
      fonts:
        - asset: assets/fonts/orbitron/Orbitron-Regular.ttf
        - asset: assets/fonts/orbitron/Orbitron-Bold.ttf
          weight: 700
        - asset: assets/fonts/orbitron/Orbitron-Medium.ttf
          weight: 500
